### ISSUE TITLE
重试方法是否可以支持抽象类或者接口

### ISSUE THREAD

**Issue by huangrg** [aizuda/snail-job#17]
public abstract class  A {
 int a;
}

public class B extends A {
int b;
}

@Retryable(scene = "testMethod", retryStrategy = RetryType.ONLY_REMOTE, isThrowException = false)
public void testMethod(A a){
 System.out.println(a);
}

类似于上面的代码其中A是一个抽象类，我是否可以对testMethod方法进行重试呢

**Comment by open-snail** [comment]
接口是支持
